projectName: my
applicationName: application
appNamespace: applications
k8sCluster: dev-k8s.myltd.lab

replicas: 1
accountName: default

app:
  javaOpts: '-Djdk.tls.client.protocols=TLSv1.2 -XX:MinRAMPercentage=80 -XX:MaxRAMPercentage=90'
  debug:
    enabled: false
    settings: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005'
  server:
    ingress:
      enabled: true
      class: internal-nginx
    url: application.apps.dev-k8s.myltd.lab
  springProfiles: kube
  logLevel: info
  resources:
    requests:
      memory: '128Mi'
      cpu: '100m'
    limits:
      memory: '512Mi'
      cpu: '500m'

supportservices:
  monitoring:
    prometheusEnabled: false
  nginxproxy:
    resources:
      requests:
        memory: '128Mi'
        cpu: '100m'
      limits:
        memory: '512Mi'
        cpu: '500m'

images:
  pullSecret: 
  app:
    registry: ghcr.io
    repository: kostakoff
    imageName: spring-application-template
    imageTag: latest
  nginxproxy:
    registry: docker.io
    repository: kostakoff
    imageName: rocky-base-images
    imageTag: 8-nginx
  tests:
    registry: docker.io
    repository: kostakoff
    imageName: rocky-base-images
    imageTag: 8-default

#### optional variables chapter, for different applications

extraVars:
  applicationConfig: | 
    server:
      port: 8080

