apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "app.fullName" . }}-service-cert
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  secretName: {{ include "app.fullName" . }}-service-cert
  secretTemplate:
    labels:
      {{- include "chart.labels" . | nindent 6 }}
  duration: 18960h # ~26 months
  renewBefore: 9480h # ~13 months
  subject:
    organizations:
      - "ORG Kostakoff"
    organizationalUnits:
      - "home"
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - server auth
  dnsNames:
    - {{ include "app.fullName" . }}.{{ .Values.appNamespace }}.svc
    - {{ include "app.fullName" . }}.{{ .Values.appNamespace }}
    - {{ include "app.fullName" . }}
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
