apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullName" . }}-nginx
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ tpl (.Files.Get "files/nginx.conf") . | indent 4 }}
