{{- if .Values.app.server.ingressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
    nginx.ingress.kubernetes.io/proxy-ssl-verify-depth: "2"
    nginx.ingress.kubernetes.io/proxy-ssl-name: '{{ include "app.fullName" . }}'
spec:
  tls:
    - hosts:
        - '{{ tpl .Values.app.server.url . }}'
  ingressClassName: nginx
  rules:
    - host: '{{ tpl .Values.app.server.url . }}'
      http:
        paths:
## main route
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullName" . }}
                port:
                  name: tcp-8443-app
{{- end }}
