apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullName" . }}-keystore
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  keystore.p12: |
{{ .Values.secrets.files.default.keyStore | indent 4 }}
  truststore.p12: |
{{ .Values.secrets.files.default.trustStore | indent 4 }}
type: Opaque