apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
stringData:
  secrets.properties: |
{{ .Values.secrets.properties | indent 4 }}
  jsec-opts.txt: |
{{ .Values.secrets.jsecOpts | indent 4 }}
type: Opaque
