apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ include "app.fullName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app: {{ include "app.fullName" . }}
    project: {{ include "app.fullName" . }}
    prometheus: enabled
spec:
  ports:
  - name: 'tcp-8443-app'
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: {{ include "app.fullName" . }}
