name: Build CI

on:
  push:
    branches: [ "master" ]

# Jobs section
jobs:
  build-mvn:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/kostakoff/rocky-base-images:8-openjdk17-mvn
      credentials:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: mvn build
        shell: bash
        env:
          M2_HOME: ${{ github.workspace	}}/.m2
        run: |
          mvn clean package --no-transfer-progress
          mvn verify
      - name: docker build application container
        run: |
          docker build . --tag ghcr.io/kostakoff/spring-application-template:latest
      - name: Push application docker container
        run: |
          docker push ghcr.io/kostakoff/spring-application-template:latest
